// <auto-generated />
using System;
using Kcg.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kcg.Migrations
{
    [DbContext(typeof(KcgContext))]
    [Migration("20240716022721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kcg.Models.TOPMenu", b =>
                {
                    b.Property<Guid>("TOPMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orders")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TOPMenuId");

                    b.ToTable("TOPMenu");

                    b.HasData(
                        new
                        {
                            TOPMenuId = new Guid("8b2bc6ff-a62d-4799-86fe-9c04b2496a9e"),
                            Icon = "Icon1",
                            Name = "網站導覽",
                            Orders = 1,
                            Url = "a1"
                        },
                        new
                        {
                            TOPMenuId = new Guid("92ca1aa4-706c-4ce3-a250-7e720f5e7239"),
                            Icon = "Icon2",
                            Name = "回首頁",
                            Orders = 2,
                            Url = "a2"
                        },
                        new
                        {
                            TOPMenuId = new Guid("afbe912a-bf31-4e9a-af47-0035bb30bbbd"),
                            Icon = "Icon3",
                            Name = "English",
                            Orders = 3,
                            Url = "a3"
                        },
                        new
                        {
                            TOPMenuId = new Guid("3f7e8247-0fa8-495a-86d9-a117a224fc7e"),
                            Icon = "Icon4",
                            Name = "雙語詞彙",
                            Orders = 4,
                            Url = "a4"
                        },
                        new
                        {
                            TOPMenuId = new Guid("29055c4d-31ff-43e0-9d1c-1a677d57889c"),
                            Icon = "Icon5",
                            Name = "市長信箱",
                            Orders = 5,
                            Url = "a5"
                        },
                        new
                        {
                            TOPMenuId = new Guid("c1e1cadf-48bf-4fb6-b1aa-5a4d9d92a81d"),
                            Icon = "Icon6",
                            Name = "洽公導覽",
                            Orders = 6,
                            Url = "a6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
